Try cat /proc/cpuinfo

diff --git a/.github/workflows/learn_cmake.yml b/.github/workflows/learn_cmake.yml
--- a/.github/workflows/learn_cmake.yml
+++ b/.github/workflows/learn_cmake.yml
@@ -53,6 +53,8 @@ jobs:
           - {c_compiler: suncc}  # TODO: установка для GitHub
           - {c_compiler: tcc}  # TODO: установка для GitHub
           # Давим из конфигурации репозитория
+          # DISABLE= macos-15, macos-15-intel, windows-latest,
+          #          cl, clang, icx, lcc, occ, pgcc, pocc, suncc, tcc,
           - os: ${{ case(contains(vars.DISABLE, ' macos-15,'),
               'macos-15', 'enable-os1') }}
           - os: ${{ case(contains(vars.DISABLE, ' macos-15-intel,'),
@@ -126,6 +128,8 @@ jobs:
       - name: Имена компиляторов с версиями, если необходимо
         shell: bash
         run: |
+          echo cat /proc/cpuinfo
+          cat /proc/cpuinfo || echo "cat FAIL: $?"
           build_type="${{ matrix.build_type }}"
           if [ -z "$build_type" ] ; then
             build_type=Release
